language: cpp

os:
  - linux

env:
#  - LIBAV=libav-stable
  - LIBAV=libav-git
#  - LIBAV=ffmpeg-stable
#  - LIBAV=ffmpeg-git

compiler:
  - clang

branches:
  only:
    - master
    - release

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y 'deb http://http.debian.net/debian wheezy-backports main'
  - sudo apt-get update
  - sudo apt-get install -y libfribidi-dev pkg-config fontconfig libsqlite3-dev yasm cmake ninja-build libqt5x11extras5-dev qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5svg5-dev
#  - sudo apt-get -t wheezy-backports install libqt5x11extras5-dev qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libqt5svg5-dev
  - TRAVIS_OS_NAME=linux; ./travis-deps libass-stable $LIBAV libmpv-git

script:
  - ./make.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#kuro-player-dev"
    on_success: change
    on_failure: always
